version: '3.8'

services:
  django:
    build: 
      context: ./django
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=your-secret-key-here
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    volumes:
      - ./django:/app
    depends_on:
      - redis
      - db

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./fastapi:/app
    environment:
      - ENVIRONMENT=development
      - DJANGO_URL=http://django:8000
    depends_on:
      - django

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=fontaine_sante_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data: 