# Generated by Django 5.2.4 on 2025-07-06 11:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExternalTaxService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('taxjar', 'TaxJar API (US Only)'), ('avalara', 'Avalara AvaTax (US/Canada/Global)'), ('cra_gst', 'Canada Revenue Agency GST Calculator'), ('manual', 'Manual Tax Calculation'), ('canadian_tax_api', 'Canadian Sales Tax API (salestaxapi.ca)')], max_length=50, unique=True)),
                ('api_key', models.CharField(blank=True, max_length=200)),
                ('api_url', models.URLField(blank=True)),
                ('supported_countries', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GLOBAL', 'Global Coverage')], default='CA', help_text='Countries supported by this tax service', max_length=10)),
                ('supports_cross_border', models.BooleanField(default=False, help_text='Whether this service can handle cross-border transactions')),
                ('supports_gst_hst', models.BooleanField(default=True, help_text='Whether this service supports Canadian GST/HST calculation')),
                ('supports_pst', models.BooleanField(default=True, help_text='Whether this service supports Provincial Sales Tax calculation')),
                ('supports_duty_calculation', models.BooleanField(default=False, help_text='Whether this service can calculate import duties')),
                ('is_active', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=1, help_text='Priority order (1 = highest priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'External Tax Service',
                'verbose_name_plural': 'External Tax Services',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['category__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='suppliermaterial',
            name='cost_per_unit',
        ),
        migrations.AddField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='is_organic',
            field=models.BooleanField(default=True, help_text='Assume all materials are organic by default'),
        ),
        migrations.AddField(
            model_name='material',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_formatted',
            field=models.TextField(blank=True, help_text='Formatted address string from geocoding service'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address_validated',
            field=models.BooleanField(default=False, help_text='Whether the address has been validated through geocoding'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, help_text='City or municipality', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='Canada', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country_code',
            field=models.CharField(default='CA', help_text='ISO country code', max_length=2),
        ),
        migrations.AddField(
            model_name='supplier',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, help_text='When the address was last geocoded', null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='geocoding_source',
            field=models.CharField(blank=True, help_text="Source of geocoding data (e.g., 'OpenStreetMap')", max_length=50),
        ),
        migrations.AddField(
            model_name='supplier',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate for mapping', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate for mapping', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(default='Unknown', help_text='Postal code or ZIP code', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='state_province',
            field=models.CharField(default='Unknown', help_text='State or province', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='street_name',
            field=models.CharField(blank=True, help_text='Street name', max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='street_number',
            field=models.CharField(blank=True, help_text='Street number', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='unit_suite',
            field=models.CharField(blank=True, help_text='Unit, suite, or apartment number', max_length=50),
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='base_cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Base cost per unit before volume discounts and taxes', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='maximum_order_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum order quantity (if any)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='minimum_order_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Minimum order quantity', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='tax_included',
            field=models.BooleanField(default=False, help_text='Whether the base cost includes taxes'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lbs', 'Pounds'), ('oz', 'Ounces'), ('l', 'Liters'), ('ml', 'Milliliters'), ('gal', 'Gallons'), ('pieces', 'Pieces'), ('boxes', 'Boxes'), ('pallets', 'Pallets')], max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text='Legacy address field - will be auto-populated from structured fields'),
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='currency',
            field=models.ForeignKey(default=1, help_text='Currency for pricing', on_delete=django.db.models.deletion.PROTECT, to='suppliers.currency'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='suppliers.materialcategory'),
        ),
        migrations.CreateModel(
            name='SeasonalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(help_text="e.g., 'Winter 2024', 'Harvest Season'", max_length=100)),
                ('start_date', models.DateField(help_text='Start date for seasonal pricing')),
                ('end_date', models.DateField(help_text='End date for seasonal pricing')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Seasonal price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_adjustment_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage adjustment from base price (positive for increase, negative for decrease)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('reason', models.CharField(blank=True, help_text="Reason for seasonal pricing (e.g., 'High demand', 'Harvest surplus')", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_pricing', to='suppliers.suppliermaterial')),
            ],
            options={
                'ordering': ['supplier_material', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TaxRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(default='CA', max_length=2)),
                ('province_state', models.CharField(blank=True, choices=[('AB', 'Alberta'), ('BC', 'British Columbia'), ('MB', 'Manitoba'), ('NB', 'New Brunswick'), ('NL', 'Newfoundland and Labrador'), ('NT', 'Northwest Territories'), ('NS', 'Nova Scotia'), ('NU', 'Nunavut'), ('ON', 'Ontario'), ('PE', 'Prince Edward Island'), ('QC', 'Quebec'), ('SK', 'Saskatchewan'), ('YT', 'Yukon')], max_length=100)),
                ('gst_rate', models.DecimalField(decimal_places=4, default=0.05, help_text='GST rate (5% for Canada)', max_digits=5)),
                ('pst_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Provincial Sales Tax rate (varies by province)', max_digits=5)),
                ('hst_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='HST rate for participating provinces (includes both GST and provincial component)', max_digits=5)),
                ('total_tax_rate', models.DecimalField(decimal_places=4, help_text='Total combined tax rate', max_digits=5)),
                ('tax_type', models.CharField(choices=[('GST', 'GST Only (5%)'), ('HST', 'Harmonized Sales Tax (GST + Provincial combined)'), ('GST_PST', 'GST + Provincial Sales Tax (separate)'), ('GST_QST', 'GST + Quebec Sales Tax'), ('SALES_TAX', 'US Sales Tax'), ('VAT', 'Value Added Tax')], default='GST', help_text='Type of tax system used', max_length=20)),
                ('is_cross_border', models.BooleanField(default=False, help_text='Whether this involves cross-border transactions')),
                ('duty_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Import duty rate for cross-border transactions', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(auto_now_add=True, help_text='Date when these tax rates became effective')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about tax rules, exemptions, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country', 'province_state', 'name'],
                'unique_together': {('country', 'province_state', 'effective_date')},
            },
        ),
        migrations.AddField(
            model_name='suppliermaterial',
            name='tax_region',
            field=models.ForeignKey(blank=True, help_text='Tax region for calculating taxes', null=True, on_delete=django.db.models.deletion.SET_NULL, to='suppliers.taxregion'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Unique warehouse code', max_length=20, unique=True)),
                ('warehouse_type', models.CharField(choices=[('distribution', 'Distribution Center'), ('fulfillment', 'Fulfillment Center'), ('storage', 'Storage Facility'), ('cold_storage', 'Cold Storage'), ('cross_dock', 'Cross-Dock Facility'), ('hub', 'Regional Hub')], default='distribution', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('street_number', models.CharField(blank=True, help_text='Street number', max_length=20)),
                ('street_name', models.CharField(blank=True, help_text='Street name', max_length=200)),
                ('unit_suite', models.CharField(blank=True, help_text='Unit, suite, or apartment number', max_length=50)),
                ('city', models.CharField(help_text='City or municipality', max_length=100)),
                ('state_province', models.CharField(help_text='State or province', max_length=100)),
                ('postal_code', models.CharField(help_text='Postal code or ZIP code', max_length=20)),
                ('country', models.CharField(default='Canada', help_text='Country', max_length=100)),
                ('country_code', models.CharField(default='CA', help_text='ISO country code', max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate for mapping', max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate for mapping', max_digits=11, null=True)),
                ('address_formatted', models.TextField(blank=True, help_text='Formatted address from geocoding')),
                ('address_validated', models.BooleanField(default=False, help_text='Address validated via geocoding')),
                ('geocoding_source', models.CharField(blank=True, help_text='Geocoding source', max_length=50)),
                ('geocoded_at', models.DateTimeField(blank=True, help_text='Last geocoded date', null=True)),
                ('storage_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='Storage capacity in cubic meters', max_digits=15, null=True)),
                ('current_utilization', models.DecimalField(blank=True, decimal_places=2, help_text='Current utilization percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('manager_name', models.CharField(blank=True, max_length=100)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('manager_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary warehouse for region')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VolumePricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=2, help_text='Minimum quantity for this pricing tier', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum quantity for this pricing tier (optional)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per unit for this quantity range', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Discount percentage from base price', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_pricing_tiers', to='suppliers.suppliermaterial')),
            ],
            options={
                'ordering': ['supplier_material', 'min_quantity'],
                'unique_together': {('supplier_material', 'min_quantity')},
            },
        ),
    ]
