# Generated by Django 5.2.4 on 2025-07-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_currency_externaltaxservice_materialcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='transportation_modes',
            field=models.JSONField(blank=True, default=list, help_text="List of supported transportation modes (e.g., ['road', 'rail', 'air'])"),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='transportation_mode',
            field=models.CharField(choices=[('road', 'Road Transport'), ('rail', 'Rail Transport'), ('air', 'Air Transport'), ('sea', 'Sea Transport'), ('mixed', 'Mixed Transport')], default='road', help_text='Primary transportation mode (legacy field, use transportation_modes for multiple)', max_length=10),
        ),
    ]
