# Generated by Django 5.2.4 on 2025-07-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplier_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliermaterial',
            name='currency',
            field=models.ForeignKey(help_text='Currency for pricing', on_delete=django.db.models.deletion.PROTECT, to='suppliers.currency'),
        ),
    ]
