# Generated by Django 5.2.4 on 2025-07-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_remove_currency_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaltaxservice',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
