# Generated by Django 4.2.x on 2025-01-03 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0006_add_null_to_api_key'),
    ]

    operations = [
        # Add new fields to Warehouse model
        migrations.AddField(
            model_name='warehouse',
            name='priority',
            field=models.CharField(
                choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')],
                default='medium',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='altitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Altitude in meters for enhanced GPS tracking',
                max_digits=8,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='geocoding_accuracy',
            field=models.CharField(
                blank=True,
                help_text='Geocoding accuracy level',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='gps_last_updated',
            field=models.DateTimeField(
                blank=True,
                help_text='Last GPS coordinate update',
                null=True
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='monitoring_enabled',
            field=models.BooleanField(
                default=True,
                help_text='Enable real-time monitoring'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='monitoring_interval',
            field=models.IntegerField(
                default=300,
                help_text='Monitoring update interval in seconds'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='geofence_radius',
            field=models.IntegerField(
                default=100,
                help_text='Geofence radius in meters for monitoring'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='supported_transport_modes',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of supported transportation modes for deliveries ['road', 'rail', 'air', 'sea']"
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='primary_transport_mode',
            field=models.CharField(
                choices=[
                    ('road', 'Road Transport'),
                    ('rail', 'Rail Transport'),
                    ('air', 'Air Transport'),
                    ('sea', 'Sea Transport'),
                    ('mixed', 'Mixed Transport')
                ],
                default='road',
                help_text='Primary transportation mode for this warehouse',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='loading_dock_count',
            field=models.IntegerField(
                default=1,
                help_text='Number of loading docks'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='max_vehicle_capacity',
            field=models.CharField(
                blank=True,
                help_text='Maximum vehicle capacity that can be accommodated',
                max_length=50
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='operates_24_7',
            field=models.BooleanField(
                default=False,
                help_text='Operates 24/7'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='operating_hours',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Operating hours by day {'monday': {'open': '09:00', 'close': '17:00'}}"
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='max_capacity_threshold',
            field=models.DecimalField(
                decimal_places=2,
                default=90.0,
                help_text='Maximum capacity threshold for alerts',
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ]
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='cold_storage_available',
            field=models.BooleanField(
                default=False,
                help_text='Cold storage capabilities'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='hazmat_certified',
            field=models.BooleanField(
                default=False,
                help_text='Hazardous materials certified'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='organic_certified',
            field=models.BooleanField(
                default=False,
                help_text='Organic handling certified'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='cross_dock_capable',
            field=models.BooleanField(
                default=False,
                help_text='Cross-docking capabilities'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='emergency_contact',
            field=models.CharField(
                blank=True,
                max_length=100
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='emergency_phone',
            field=models.CharField(
                blank=True,
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='max_supplier_distance',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Maximum preferred distance from suppliers (km)',
                max_digits=8,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='avg_delivery_time',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Average delivery time in hours',
                max_digits=6,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='on_time_delivery_rate',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='On-time delivery rate percentage',
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100)
                ]
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='last_performance_update',
            field=models.DateTimeField(
                blank=True,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='accepts_new_suppliers',
            field=models.BooleanField(
                default=True,
                help_text='Accepts new supplier registrations'
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='last_monitoring_check',
            field=models.DateTimeField(
                blank=True,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='monitoring_status',
            field=models.CharField(
                choices=[
                    ('online', 'Online'),
                    ('offline', 'Offline'),
                    ('maintenance', 'Maintenance'),
                    ('alert', 'Alert')
                ],
                default='online',
                max_length=20
            ),
        ),
        
        # Add new warehouse type choices
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(
                choices=[
                    ('distribution', 'Distribution Center'),
                    ('fulfillment', 'Fulfillment Center'),
                    ('storage', 'Storage Facility'),
                    ('cold_storage', 'Cold Storage'),
                    ('cross_dock', 'Cross-Dock Facility'),
                    ('hub', 'Regional Hub'),
                    ('consolidation', 'Consolidation Center'),
                    ('retail', 'Retail Store'),
                    ('manufacturing', 'Manufacturing Facility')
                ],
                default='distribution',
                max_length=20
            ),
        ),
        
        # Create many-to-many relationship for preferred suppliers
        migrations.CreateModel(
            name='WarehousePreferredSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.warehouse')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'unique_together': {('warehouse', 'supplier')},
            },
        ),
        
        # Add the many-to-many field
        migrations.AddField(
            model_name='warehouse',
            name='preferred_suppliers',
            field=models.ManyToManyField(
                blank=True,
                help_text='Preferred suppliers for this warehouse',
                related_name='preferred_warehouses',
                to='suppliers.supplier'
            ),
        ),
        
        # Update warehouse meta options
        migrations.AlterModelOptions(
            name='warehouse',
            options={
                'ordering': ['-is_primary', 'priority', 'name']
            },
        ),
        
        # Add database indexes for performance
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['latitude', 'longitude'], name='suppliers_warehouse_lat_lng_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['is_active', 'monitoring_enabled'], name='suppliers_warehouse_active_monitoring_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_type', 'is_active'], name='suppliers_warehouse_type_active_idx'),
        ),
        
        # Update help text for latitude/longitude fields
        migrations.AlterField(
            model_name='warehouse',
            name='latitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text='Latitude coordinate for mapping and real-time monitoring',
                max_digits=10,
                null=True
            ),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='longitude',
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text='Longitude coordinate for mapping and real-time monitoring',
                max_digits=11,
                null=True
            ),
        ),
    ] 