# Generated by Django 5.2.4 on 2025-09-05 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_enhance_warehouse_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseCapacityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('capacity_warning', 'Capacity Warning'), ('capacity_critical', 'Capacity Critical'), ('capacity_full', 'Capacity Full'), ('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock Alert')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=15)),
                ('message', models.TextField(help_text='Alert message')),
                ('current_utilization', models.DecimalField(blank=True, decimal_places=2, help_text='Current utilization percentage when alert was created', max_digits=5, null=True)),
                ('threshold_exceeded', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold that was exceeded', max_digits=5, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Current quantity in stock', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity reserved for pending orders', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Available quantity (current - reserved)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_volume_m3', models.DecimalField(decimal_places=2, default=0, help_text='Total volume occupied by this material', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, help_text='Total weight of this material in stock', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock_level', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum stock level alert threshold', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_stock_level', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum stock level', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_restocked_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['warehouse__name', 'material__name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='warehousepreferredsupplier',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='warehousepreferredsupplier',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='warehousepreferredsupplier',
            name='warehouse',
        ),
        migrations.RenameIndex(
            model_name='warehouse',
            new_name='suppliers_w_latitud_6c3509_idx',
            old_name='suppliers_warehouse_lat_lng_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouse',
            new_name='suppliers_w_is_acti_e11653_idx',
            old_name='suppliers_warehouse_active_monitoring_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouse',
            new_name='suppliers_w_warehou_06e374_idx',
            old_name='suppliers_warehouse_type_active_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='destination_warehouse',
            field=models.ForeignKey(default=1, help_text='Warehouse where materials will be delivered', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_orders', to='suppliers.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_co2_emissions',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated CO2 emissions (kg CO2e)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated distance from supplier to warehouse (km)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_transport_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated transportation cost', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='total_volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total volume of materials in cubic meters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total weight of materials in kilograms', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='transport_mode',
            field=models.CharField(choices=[('truck', 'Truck'), ('train', 'Train'), ('ship', 'Ship'), ('plane', 'Plane'), ('mixed', 'Mixed Transport')], default='truck', help_text='Transportation mode for this order', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_volume_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total volume (quantity × volume_per_unit)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total weight (quantity × weight_per_unit)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='volume_per_unit_m3',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Volume per unit in cubic meters', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_per_unit_kg',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Weight per unit in kilograms', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='warehousecapacityalert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousecapacityalert',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Related material for stock alerts', null=True, on_delete=django.db.models.deletion.CASCADE, to='suppliers.material'),
        ),
        migrations.AddField(
            model_name='warehousecapacityalert',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_alerts', to='suppliers.warehouse'),
        ),
        migrations.AddField(
            model_name='warehouseinventory',
            name='last_restocked_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restocked_inventory', to='suppliers.order'),
        ),
        migrations.AddField(
            model_name='warehouseinventory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stocks', to='suppliers.material'),
        ),
        migrations.AddField(
            model_name='warehouseinventory',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='suppliers.warehouse'),
        ),
        migrations.DeleteModel(
            name='WarehousePreferredSupplier',
        ),
        migrations.AddIndex(
            model_name='warehousecapacityalert',
            index=models.Index(fields=['warehouse', 'status'], name='suppliers_w_warehou_f595f4_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousecapacityalert',
            index=models.Index(fields=['alert_type', 'status'], name='suppliers_w_alert_t_f8881e_idx'),
        ),
        migrations.AddIndex(
            model_name='warehousecapacityalert',
            index=models.Index(fields=['created_at'], name='suppliers_w_created_08c854_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinventory',
            index=models.Index(fields=['warehouse', 'material'], name='suppliers_w_warehou_96ad65_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinventory',
            index=models.Index(fields=['current_quantity'], name='suppliers_w_current_6cf555_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouseinventory',
            index=models.Index(fields=['available_quantity'], name='suppliers_w_availab_7e06e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouseinventory',
            unique_together={('warehouse', 'material')},
        ),
    ]
