import { RawMaterial, Supplier } from "@/types/types";

export const testData = {
  rawMaterials: [
    {
      id: "1",
      name: "Organic Quinoa",
      type: "Grain",
      description: "High-quality organic quinoa from sustainable farms",
      quantity: 1000,
      unit: "kg",
      suppliers: ["1", "2"],
      quality: {
        score: 95,
        defectRate: 0.01,
        consistencyScore: 0.98,
      },
      environmentalData: {
        carbonFootprint: 50,
        waterUsage: 200,
        landUse: 500,
        biodiversityImpact: "Low",
      },
      economicData: {
        unitCost: 8.5,
        transportationCost: 1.2,
        storageCost: 0.5,
        totalCostPerUnit: 10.2,
        taxRate: 0.1,
        tariffRate: 0.05,
        leadTime: 5,
        paymentTerms: "Net 30",
        currency: "USD",
      },
    },
    {
      id: "2",
      name: "Fresh Basil",
      type: "Vegetable",
      description: "Fresh organic basil leaves",
      quantity: 500,
      unit: "kg",
      suppliers: ["2", "3"],
      quality: {
        score: 90,
        defectRate: 0.02,
        consistencyScore: 0.95,
      },
      environmentalData: {
        carbonFootprint: 30,
        waterUsage: 150,
        landUse: 300,
        biodiversityImpact: "Low",
      },
      economicData: {
        unitCost: 12.0,
        transportationCost: 2.0,
        storageCost: 1.0,
        totalCostPerUnit: 15.0,
        taxRate: 0.1,
        tariffRate: 0.05,
        leadTime: 3,
        paymentTerms: "Net 30",
        currency: "USD",
      },
    },
  ],
  suppliers: [
    {
      id: "1",
      name: "Sustainable Grains Co.",
      location: {
        address: "123 Farm Road, Portland, OR 97201",
        coordinates: {
          lat: 45.5155,
          lng: -122.6789,
        },
      },
      quality: {
        score: 95,
        certifications: ["ISO 9001", "ISO 14001", "Organic Certified"],
        lastAudit: "2024-03-15",
      },
      environmentalData: {
        carbonFootprint: 150,
        energyEfficiency: "High",
        wasteManagement: "Excellent",
        waterUsage: 1000,
        emissions: 500,
      },
      economicData: {
        foundedYear: 2010,
        annualRevenue: 5000000,
        employeeCount: 250,
        materialCosts: 50000,
        transportationCosts: 15000,
        storageCosts: 8000,
        totalCost: 73000,
        costPerUnit: 73,
      },
      materials: ["1"],
      certifications: ["ISO 9001", "ISO 14001", "Organic Certified"],
      transportMode: "truck",
      distance: 150,
      productionCapacity: "1000 units/day",
      leadTime: 5,
      reliability: 0.95,
      transportationDetails: "Standard truck delivery with temperature control",
      contactInfo: {
        name: "John Doe",
        email: "john@sustainablegrains.com",
        phone: "123-456-7890",
      },
      operatingHours: "8:00-17:00",
      performanceHistory: "Consistent performance with average score of 95",
      riskScore: 0.05,
    },
    {
      id: "2",
      name: "Fresh Produce Solutions",
      location: {
        address: "456 Market Street, San Francisco, CA 94105",
        coordinates: {
          lat: 37.7749,
          lng: -122.4194,
        },
      },
      quality: {
        score: 92,
        certifications: ["ISO 9001", "Organic Certified"],
        lastAudit: "2024-03-10",
      },
      environmentalData: {
        carbonFootprint: 120,
        energyEfficiency: "Medium",
        wasteManagement: "Good",
        waterUsage: 800,
        emissions: 400,
      },
      economicData: {
        foundedYear: 2015,
        annualRevenue: 3500000,
        employeeCount: 180,
        materialCosts: 55000,
        transportationCosts: 16000,
        storageCosts: 8500,
        totalCost: 79500,
        costPerUnit: 79.5,
      },
      materials: ["1", "2"],
      certifications: ["ISO 9001", "Organic Certified"],
      transportMode: "train",
      distance: 300,
      productionCapacity: "800 units/day",
      leadTime: 7,
      reliability: 0.98,
      transportationDetails: "Rail transport with specialized containers",
      contactInfo: {
        name: "Jane Smith",
        email: "jane@freshproduce.com",
        phone: "234-567-8901",
      },
      operatingHours: "7:00-16:00",
      performanceHistory: "Excellent performance with improving trend",
      riskScore: 0.08,
    },
    {
      id: "3",
      name: "Local Farm Co-op",
      location: {
        address: "789 Rural Route, Sacramento, CA 95814",
        coordinates: {
          lat: 38.5816,
          lng: -121.4944,
        },
      },
      quality: {
        score: 88,
        certifications: ["Organic Certified"],
        lastAudit: "2024-03-01",
      },
      environmentalData: {
        carbonFootprint: 100,
        energyEfficiency: "High",
        wasteManagement: "Excellent",
        waterUsage: 600,
        emissions: 300,
      },
      economicData: {
        foundedYear: 2005,
        annualRevenue: 2800000,
        employeeCount: 150,
        materialCosts: 48000,
        transportationCosts: 14000,
        storageCosts: 7500,
        totalCost: 69500,
        costPerUnit: 69.5,
      },
      materials: ["2"],
      certifications: ["Organic Certified"],
      transportMode: "truck",
      distance: 100,
      productionCapacity: "600 units/day",
      leadTime: 3,
      reliability: 0.92,
      transportationDetails: "Local delivery with refrigerated trucks",
      contactInfo: {
        name: "Bob Wilson",
        email: "bob@localfarm.com",
        phone: "345-678-9012",
      },
      operatingHours: "9:00-18:00",
      performanceHistory: "Stable performance with good quality",
      riskScore: 0.12,
    },
  ],
}; 